[package]
name = "stack_script"
version = "0.1.0"
authors = ["Ben Findley <ben.g.findley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
either = "1.5"
lazy_static = "1.4"
rand = "0.7"
